USE MesaAyuda

CREATE PROC ShowEmployees AS
SELECT * FROM Employees GO

CREATE PROC ShowAreas AS
SELECT * FROM Areas GO

EXEC ShowAreas

ALTER TABLE Areas 
ALTER COLUMN fk_Employee VARCHAR(20) NULL

ALTER TABLE Employees
ALTER COLUMN fk_EmployeeBoss VARCHAR(20) NULL