
CREATE DATABASE MESA_AYUDA

USE MESA_AYUDA

CREATE TABLE AREAS(
	IDAREA INT IDENTITY(1,1) PRIMARY KEY,
	CODE AS ('AR'+RIGHT ('00' + CONVERT(VARCHAR,IDAREA),(2))),
	NAME VARCHAR(50) NOT NULL,
	FKEMPLOYEE INT,
)

CREATE TABLE EMPLOYEES(
	IDEMPLOYEE INT IDENTITY(1,1) PRIMARY KEY,
	CODE AS ('EMP'+RIGHT ('00' + CONVERT(VARCHAR,IDEMPLOYEE),(2))),
	NAME VARCHAR(100) NOT NULL,
	PHOTO VARCHAR(200),
	CVEMPLOYEE VARCHAR(200),
	TELEPHONE VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	ADDRESS VARCHAR(100) NOT NULL,
	CORDX DECIMAL(10,7),
	CORDY DECIMAL(10,7),
	FKEMPLOYEEBOSS INT,
	FKAREA INT,
)

ALTER TABLE AREAS ADD CONSTRAINT CONST_AEMPLOYEE
FOREIGN KEY(FKEMPLOYEE) REFERENCES EMPLOYEES(IDEMPLOYEE)

ALTER TABLE EMPLOYEES ADD CONSTRAINT CONST_EAREA
FOREIGN KEY(FKAREA) REFERENCES AREAS(IDAREA)

ALTER TABLE EMPLOYEES ADD CONSTRAINT CONST_EBOSS
FOREIGN KEY(FKEMPLOYEEBOSS) REFERENCES EMPLOYEES(IDEMPLOYEE)

CREATE TABLE Status(
	Id VARCHAR(1) PRIMARY KEY,
	Name VARCHAR(16) NOT NULL,
)

CREATE TABLE Requirements(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	fk_Area VARCHAR(10) NOT NULL
)

ALTER TABLE Requirements
ADD CONSTRAINT CONSTfk_Area2 FOREIGN KEY(fk_Area) REFERENCES Areas(Id)

CREATE TABLE Requirements_Details(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Date DATETIME NOT NULL,
	Observation VARCHAR(4000) NOT NULL,
	fk_Requirement INT NOT NULL,
	fk_Status VARCHAR(1) NOT NULL,
	fk_Employee VARCHAR(20) NOT NULL,
	fk_AssignedEmployee VARCHAR(20)
)


ALTER TABLE Requirements_Details
ADD CONSTRAINT CONSTfk_Requirement FOREIGN KEY(fk_Requirement) 
REFERENCES Requirements(Id)

ALTER TABLE Requirements_Details
ADD CONSTRAINT CONSTfk_Status FOREIGN KEY(fk_Status) 
REFERENCES Status(Id)

ALTER TABLE Requirements_Details
ADD CONSTRAINT CONSTfk_Employee2 FOREIGN KEY(fk_Employee)
REFERENCES Employees(Id)

ALTER TABLE Requirements_Details
ADD CONSTRAINT CONSTfk_AssignedEmployee FOREIGN KEY(fk_AssignedEmployee)
REFERENCES Employees(Id)

CREATE TABLE Appointments(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
)

CREATE TABLE Appointments_Employees(
	fk_Appointment INT NOT NULL,
	fk_Employee VARCHAR(20) NOT NULL,
	Start_Date DATE NOT NULL,
	End_Date DATE,
	PRIMARY KEY(fk_Appointment,fk_Employee)
)
ALTER TABLE Appointments_Employees
ADD CONSTRAINT CONSTfk_Appointment FOREIGN KEY(fk_Appointment) 
REFERENCES Appointments(Id)

ALTER TABLE Appointments_Employees
ADD CONSTRAINT CONSTfk_Employee3 FOREIGN KEY(fk_Employee)
REFERENCES Employees(Id)