
--########################AREAS
--CREATE
CREATE PROC SP_GETAREAS
AS
SELECT * FROM AREAS

CREATE PROC SP_SEARCHAREA
@NAMEAREA VARCHAR(50)
AS
SELECT * FROM AREAS
WHERE NAME LIKE @NAMEAREA + '%'

--INSERT

CREATE PROC SP_INSERTAREA
@NAME VARCHAR(50),
@MANAGER INT
AS
INSERT INTO AREAS VALUES(@NAME,@MANAGER)

--EDIT

CREATE PROC SP_EDITAREA
@IDAREA INT,
@NAME VARCHAR(50),
@MANAGER INT
AS
UPDATE AREAS SET NAME = @NAME, FKEMPLOYEE = @MANAGER
WHERE IDAREA = @IDAREA

--DELETE

CREATE PROC SP_DELETEAREA
@IDAREA INT
AS
DELETE AREAS WHERE IDAREA = @IDAREA

--########################EMPLOYEES
--CREATE
CREATE PROC SP_GETEMPLOYEES
AS
SELECT * FROM EMPLOYEES



--INSERT
CREATE PROC SP_INSERTEMPLOYEE
@NAME VARCHAR(50),
@PHOTO VARCHAR(200),
@CVEMPLOYEE VARCHAR(200),
@TELEPHONE VARCHAR(15),
@EMAIL VARCHAR(100),
@ADDRESS VARCHAR(100),
@CORDX DECIMAL(10,7),
@CORDY DECIMAL(10,7),
@FKEMPLOYEEBOSS INT,
@FKAREA INT
AS
INSERT INTO EMPLOYEES VALUES(@NAME,@PHOTO,@CVEMPLOYEE,@TELEPHONE,@EMAIL,@ADDRESS,@CORDX,@CORDY,@FKEMPLOYEEBOSS,@FKAREA)

--EDIT

CREATE PROC SP_EDITEMPLOYEE
@IDEMPLOYEE INT,
@NAME VARCHAR(50),
@PHOTO VARCHAR(200),
@CVEMPLOYEE VARCHAR(200),
@TELEPHONE VARCHAR(15),
@EMAIL VARCHAR(100),
@ADDRESS VARCHAR(100),
@CORDX DECIMAL(10,7),
@CORDY DECIMAL(10,7),
@FKEMPLOYEEBOSS INT,
@FKAREA INT
AS
UPDATE EMPLOYEES SET 
NAME=@NAME,PHOTO=@PHOTO,CVEMPLOYEE=@CVEMPLOYEE,TELEPHONE=@TELEPHONE,EMAIL=@EMAIL,ADDRESS=@ADDRESS,CORDX=@CORDX,CORDY=@CORDY,FKEMPLOYEEBOSS=@FKEMPLOYEEBOSS,FKAREA=@FKAREA
WHERE IDEMPLOYEE = @IDEMPLOYEE

--DELETE

CREATE PROC SP_DELETEEMPLOYEE
@IDEMPLOYEE INT
AS
DELETE EMPLOYEES WHERE IDEMPLOYEE = @IDEMPLOYEE