CREATE TABLE Areas(
	Id VARCHAR(10) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	fk_Employee VARCHAR(20)
)

CREATE TABLE Employees(
	Id VARCHAR(20) PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Photo VARCHAR(200),
	Employee_CV VARCHAR(200),
	Telephone VARCHAR(15) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Address VARCHAR(100) NOT NULL,
	Cord_X DECIMAL(10,7),
	Cord_Y DECIMAL(10,7),
	fk_EmployeeBoss VARCHAR(20),
	fk_Area VARCHAR(10) NOT NULL,
)

ALTER TABLE Areas ADD CONSTRAINT CONSTfk_Employee 
FOREIGN KEY(fk_Employee) REFERENCES Employees(Id)

ALTER TABLE Employees ADD CONSTRAINT CONSTfk_Area 
FOREIGN KEY(fk_Area) REFERENCES Areas(Id)

ALTER TABLE Employees ADD CONSTRAINT CONSTfk_EmployeeBoss 
FOREIGN KEY(fk_EmployeeBoss) REFERENCES Employees(Id)

CREATE TABLE Status(
	Id VARCHAR(1) PRIMARY KEY,
	Name VARCHAR(16) NOT NULL,
)

CREATE TABLE REQUIREMENTS(
	Id INT IDENTITY(1,1) PRIMARY KEY,

)